# Generated by Django 3.2.7 on 2021-09-30 18:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deckapp', '0005_alter_deck_group_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='amount_limit',
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1000000)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deck_msg', to='deckapp.deck')),
                ('user', models.ManyToManyField(blank=True, related_name='user_msg', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
