# Generated by Django 3.2.7 on 2021-10-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deckapp', '0011_remove_user_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='group_profile',
            field=models.ImageField(default='static/img/groupofpeople.png', upload_to='uploads/'),
        ),
    ]
