# Generated by Django 3.2.7 on 2021-10-12 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deckapp', '0014_auto_20211009_1134'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeckRequest',
        ),
    ]
