# Generated by Django 3.2.7 on 2021-09-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deckapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='amount_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deck',
            name='users_limit',
            field=models.IntegerField(default=0),
        ),
    ]
