# Generated by Django 3.2.7 on 2021-09-24 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deckapp', '0002_auto_20210922_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='group_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SecuritKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keys', models.CharField(max_length=50)),
                ('decks', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deck_keys', to='deckapp.deck')),
            ],
        ),
    ]
