# Generated by Django 3.2.7 on 2021-09-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deckapp', '0003_auto_20210924_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='group_profile',
            field=models.ImageField(blank=True, upload_to='uploads/groups/'),
        ),
    ]
