# Generated by Django 3.2.7 on 2021-10-04 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deckapp', '0010_auto_20211002_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mobile_number',
        ),
    ]
