# Generated by Django 3.2.7 on 2021-10-15 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deckapp', '0016_securitykeys'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SecuritKeys',
        ),
    ]
